
import React from 'react';
import StepContainer from '../StepContainer';
import CodeBlock from '../CodeBlock';
import { ProjectState } from '../../types';

interface BackendCodeStepProps {
  projectState: ProjectState;
  onBack: () => void;
  onNext: () => void;
}

const BackendCodeStep: React.FC<BackendCodeStepProps> = ({
  projectState,
  onBack,
  onNext,
}) => {
  const { allCode } = projectState;
  const backendFiles = allCode.backend;
  const isGenerated = !!backendFiles;

  const renderContent = () => {
    if (!isGenerated) {
       return (
        <div className="text-center p-8 bg-gray-900/50 rounded-lg border border-gray-700">
            <p className="text-lg text-gray-400">Backend code will be generated here by the orchestration agent.</p>
        </div>
      );
    }
    return (
       <div className="space-y-8">
          <div>
            <h3 className="text-lg font-semibold text-white mb-2">File: backend/package.json</h3>
            <CodeBlock code={backendFiles.packageJson} language="json" />
          </div>
          <div>
            <h3 className="text-lg font-semibold text-white mb-2">File: backend/src/server.ts</h3>
            <CodeBlock code={backendFiles.serverTs} language="typescript" />
          </div>
          <div>
            <h3 className="text-lg font-semibold text-white mb-2">File: backend/src/api/routes.ts</h3>
            <CodeBlock code={backendFiles.routesTs} language="typescript" />
          </div>
          <div className="border-t border-gray-700 pt-6">
            <h3 className="text-lg font-semibold text-white mb-4">Setup Commands</h3>
            <p className="text-gray-400 mb-4">Run these commands from your `backend/` directory:</p>
            <CodeBlock code={"npm install\nnpm run dev\n# In another terminal:\ncurl http://localhost:8080/health"} />
          </div>
        </div>
    );
  }

  return (
    <StepContainer
      title="Step E: Backend Code Generation"
      description="Production-ready TypeScript backend generated by the agent based on your frontend requirements."
      onBack={onBack}
      onNext={onNext}
      isNextDisabled={!isGenerated}
    >
      {renderContent()}
    </StepContainer>
  );
};

export default BackendCodeStep;
