
import React from 'react';
import StepContainer from '../StepContainer';
import CodeBlock from '../CodeBlock';
import { ProjectState } from '../../types';

interface TerraformStepProps {
  projectState: ProjectState;
  onBack: () => void;
  onNext: () => void;
}

const TerraformStep: React.FC<TerraformStepProps> = ({ 
  projectState,
  onBack, 
  onNext, 
}) => {
  const { config, allCode } = projectState;
  const terraformCode = allCode.terraform;
  const isGenerated = !!terraformCode;

  const renderContent = () => {
    if (!isGenerated) {
      return (
        <div className="text-center p-8 bg-gray-900/50 rounded-lg border border-gray-700">
            <p className="text-lg text-gray-400">Terraform code will be generated here by the orchestration agent.</p>
            <p className="text-sm text-gray-500 mt-2">Start the automation from the controls above to begin.</p>
        </div>
      );
    }

    return (
      <div className="space-y-8">
        <div className="p-4 bg-cyan-900/20 border border-cyan-500/30 rounded-lg">
          <p className="text-cyan-200 text-sm">
            ✨ This Terraform code was generated by the Generation Agent based on your project's architecture plan.
          </p>
        </div>
        <div>
          <h3 className="text-lg font-semibold text-white mb-2">File: terraform/main.tf</h3>
          <CodeBlock code={terraformCode.main || ''} language="hcl" />
        </div>
        <div>
          <h3 className="text-lg font-semibold text-white mb-2">File: terraform/variables.tf</h3>
          <CodeBlock code={terraformCode.variables || ''} language="hcl" />
        </div>
        <div>
          <h3 className="text-lg font-semibold text-white mb-2">File: terraform/outputs.tf</h3>
          <CodeBlock code={terraformCode.outputs || ''} language="hcl" />
        </div>
        <div>
          <h3 className="text-lg font-semibold text-white mb-2">File: terraform/terraform.tfvars</h3>
          <p className="text-sm text-gray-400 mb-2">
            Replace placeholders with your actual {config.cloud.toUpperCase()} project/account ID.
          </p>
          <CodeBlock code={terraformCode.tfvars || ''} language="hcl" />
        </div>
        <div className="border-t border-gray-700 pt-6">
          <h3 className="text-lg font-semibold text-white mb-4">Deployment Commands</h3>
          <p className="text-gray-400 mb-4">Run these commands from your `terraform/` directory:</p>
          <CodeBlock code={"terraform init\nterraform plan\nterraform apply"} />
        </div>
      </div>
    );
  };

  return (
    <StepContainer
      title="Step D: Deploy Infrastructure with Terraform"
      description="The agent has generated custom Terraform code. Save these files and follow the commands below."
      onBack={onBack}
      onNext={onNext}
      isNextDisabled={!isGenerated}
    >
      {renderContent()}
    </StepContainer>
  );
};

export default TerraformStep;
